# Generated by Django 4.2 on 2023-04-14 01:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(default=users.models.getRandomString, max_length=20, verbose_name='验证码'),
        ),
    ]
