# Generated by Django 4.1.7 on 2023-04-07 08:43

import chatapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('sessionId', models.CharField(default=chatapp.models.getUniqueId, max_length=50, primary_key=True, serialize=False, verbose_name='会话ID')),
                ('sessionName', models.CharField(default='新会话', max_length=10, verbose_name='会话名称')),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('endTime', models.DateTimeField(blank=True, null=True, verbose_name='上次访问时间')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(null=True, verbose_name='消息内容')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.conversation', verbose_name='会话信息')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
            },
        ),
    ]
