# Generated by Django 4.1.7 on 2023-04-07 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechToText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=512, verbose_name='处理音频名称')),
                ('filePath', models.FileField(max_length=128, upload_to='audios/%Y/%m', verbose_name='处理音频路径')),
                ('handleTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
                ('finishTime', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('times', models.IntegerField(default=0, null=True, verbose_name='转换时长')),
            ],
            options={
                'verbose_name': '处理任务',
                'verbose_name_plural': '处理任务',
            },
        ),
    ]
