# Generated by Django 4.1.7 on 2023-04-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sttapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtotext',
            name='content',
            field=models.TextField(default='', null=True, verbose_name='转换内容'),
        ),
    ]
